name: Deployment Workflow
on:
    push:
        branches: [ main ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing server connection
      uses: appleboy/ssh-action@master
      with: 
        host: api.theorbits.tech
        username: sahil
        key: ${{ secrets.ACCESS_SECRET }}
        port: 22
        script: |
          cd api/
          git pull
          npm install
          pm2 restart 0 --update-env


